from graphcalc.additive_combinatorics.ambient_groups import (
    Element,
    FiniteAbelianGroup,
)
from graphcalc.additive_combinatorics.sets import AdditiveSet

from graphcalc.additive_combinatorics.generators import (
    all_subsets_of_group,
    arithmetic_progression,
    coset,
    empty_set,
    interval,
    random_subset,
    random_symmetric_subset,
    sample_random_subsets,
    singleton,
    subgroup_from_generators,
    union_of_cosets,
    whole_group,
)

from graphcalc.additive_combinatorics.invariants import (
    additive_energy,
    cardinality,
    diffset_defect,
    diffset_density,
    diffset_size,
    difference_constant,
    doubling_constant,
    doubling_minus_difference,
    energy_over_sumset_square,
    max_difference_representation_count,
    max_sum_representation_count,
    normalized_additive_energy,
    stabilizer_index,
    stabilizer_size,
    stabilizer_size_of_sumset,
    sumset_defect,
    sumset_density,
    sumset_size,
    sumset_stabilizer_index,
    tripling_constant,
)

from graphcalc.additive_combinatorics.properties import (
    contains_zero,
    has_full_diffset,
    has_full_sumset,
    has_small_doubling,
    is_aperiodic,
    is_coset,
    is_difference_larger_than_sumset,
    is_doubling_at_most_2,
    is_doubling_at_most_3_over_2,
    is_empty_set,
    is_periodic,
    is_sidon,
    is_subgroup,
    is_sum_free,
    is_symmetric,
    is_trivial_set,
    is_whole_group,
    sumset_is_periodic,
)

from graphcalc.additive_combinatorics.dataset_generators import (
    additive_dataset_column_definitions,
    additive_set_to_record,
    generate_additive_set_dataset,
    large_additive_snapshot,
    medium_additive_snapshot,
    small_additive_snapshot,
)

from graphcalc.additive_combinatorics.dataset_exports import (
    additive_package_to_dataframe,
    additive_rows_to_dataframe,
    save_additive_column_definitions_json,
    save_additive_metadata_json,
    save_additive_package_csv,
)

__all__ = [
    # Core objects
    "Element",
    "FiniteAbelianGroup",
    "AdditiveSet",
    # Generators
    "empty_set",
    "whole_group",
    "singleton",
    "interval",
    "arithmetic_progression",
    "random_subset",
    "random_symmetric_subset",
    "sample_random_subsets",
    "subgroup_from_generators",
    "coset",
    "union_of_cosets",
    "all_subsets_of_group",
    # Invariants
    "cardinality",
    "sumset_size",
    "diffset_size",
    "doubling_constant",
    "difference_constant",
    "tripling_constant",
    "sumset_defect",
    "diffset_defect",
    "doubling_minus_difference",
    "sumset_density",
    "diffset_density",
    "additive_energy",
    "normalized_additive_energy",
    "energy_over_sumset_square",
    "max_sum_representation_count",
    "max_difference_representation_count",
    "stabilizer_size",
    "stabilizer_size_of_sumset",
    "stabilizer_index",
    "sumset_stabilizer_index",
    # Predicates
    "contains_zero",
    "is_empty_set",
    "is_trivial_set",
    "is_whole_group",
    "is_symmetric",
    "is_subgroup",
    "is_coset",
    "is_sum_free",
    "is_sidon",
    "has_small_doubling",
    "is_doubling_at_most_3_over_2",
    "is_doubling_at_most_2",
    "has_full_sumset",
    "has_full_diffset",
    "is_difference_larger_than_sumset",
    "is_periodic",
    "is_aperiodic",
    "sumset_is_periodic",
    # Dataset generation
    "additive_dataset_column_definitions",
    "additive_set_to_record",
    "generate_additive_set_dataset",
    "small_additive_snapshot",
    "medium_additive_snapshot",
    "large_additive_snapshot",
    # Dataset export
    "additive_rows_to_dataframe",
    "additive_package_to_dataframe",
    "save_additive_package_csv",
    "save_additive_column_definitions_json",
    "save_additive_metadata_json",
]
