name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Unit and Docstring
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install LP/MIP solvers (HiGHS, CBC, GLPK)
        run: |
          sudo apt-get update
          sudo apt-get install -y highs coinor-cbc glpk-utils

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run unit tests
        run: pytest

      - name: Run docstring examples
        run: pytest --doctest-modules -v src/
